apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-basic-1777535148859
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/e2e-basic-1777535148859:github-78fb784d0f74271a35924f77cb9dc5191da743a2
          name: container-image
